name: Pull actions

on:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: "actions/checkout@v2"

        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"
            ignore: brands

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"
  lint:
    runs-on: ubuntu-latest
    name: pyLint Check
    steps:
      - uses: actions/checkout@v2
      - uses: dmamontov/hass-py-lint@main
        with:
          hass-version: ">=2022.3.0"
          path: "custom_components/traeger"
          use-pylint: true
          use-black: false
          use-mypy: false
          extra-pylint-options: "--disable=import-error,C0103"
          extra-black-options: ""
          extra-mypy-options: ""
          use-hass-branch: false
  black:
    runs-on: ubuntu-latest
    name: Black Check
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable     
